apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-reactive-user-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-reactive-user-service-deployment
  template:
    metadata:
      labels:
        app: spring-reactive-user-service-deployment
    spec:
      containers:
        - name: spring-reactive-user-service-deployment
          env:
            - name: R2DBC_URI
              valueFrom:
                configMapKeyRef:
                  name: user-r2dbc-config
                  key: spring.r2dbc.url
            - name: R2DBC_USERNAME
                valueFrom:
                  configMapKeyRef:
                    name: user-r2dbc-config
                    key: spring.r2dbc.username
            - name: R2DBC_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: user-r2dbc-config
                    key: spring.r2dbc.password
          image: vogetisameer12/spring-reactive-user-service:latest